services:
  bitwarden:
    depends_on:
      bitwarden-db:
        condition: service_healthy
    image: bitwarden/self-host:dev
    env_file:
      - settings.env
    restart: always
    ports:
      - "8080:8080"  # HTTP - for certificate renewal
      - "8443:8443"  # HTTPS
    volumes:
      - bitwarden:/etc/bitwarden
      - logs:/var/log/bitwarden
      - ./ssl:/etc/bitwarden/ssl:ro
      - ./bitwarden-ssl.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/alive"]
      interval: 30s
      timeout: 10s
      retries: 3

  bitwarden-db:
    environment:
      POSTGRES_USER: "bitwarden"
      POSTGRES_DB: "bitwarden_vault"
      POSTGRES_PASSWORD_FILE: "/run/secrets/postgres_password"
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
    secrets:
      - postgres_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bitwarden -d bitwarden_vault"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  bitwarden:
  logs:
  data:

secrets:
  postgres_password:
    file: ./postgres_password.txt
